CREATE TABLE tour_booking
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    surname       VARCHAR(255)                            NOT NULL,
    tour_offer_id BIGINT                                  NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_tourbooking PRIMARY KEY (id)
);

ALTER TABLE tour_booking
    ADD CONSTRAINT FK_TOURBOOKING_ON_TOUR_OFFER FOREIGN KEY (tour_offer_id) REFERENCES tour_offers (id);

ALTER TABLE tour_booking
    ADD CONSTRAINT FK_TOURBOOKING_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);