CREATE TABLE tour_offers
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tour_id BIGINT,
    user_id BIGINT,
    price   DECIMAL,
    profit  DECIMAL,
    status  VARCHAR(255),
    CONSTRAINT pk_tour_offers PRIMARY KEY (id)
);

ALTER TABLE tour_offers
    ADD CONSTRAINT FK_TOUR_OFFERS_ON_TOUR FOREIGN KEY (tour_id) REFERENCES tours (id);

ALTER TABLE tour_offers
    ADD CONSTRAINT FK_TOUR_OFFERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);