CREATE TABLE tours
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    location    VARCHAR(255)                            NOT NULL,
    start_time  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    finish_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_tours PRIMARY KEY (id)
);